server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-projects
          uri: 'http://localhost:8092'
          predicates:
            - Path=/api/proyectos/**
        - id: msvc-users
          uri: 'http://localhost:8100'
          predicates:
            - Path=/api/usuarios/**
          filters:
            - name: AuthFilter
        - id: msvc-annotation
          uri: 'http://localhost:8095'
          predicates:
            - Path=/api/anotaciones/**
        - id: msvc-auth
          uri: 'http://localhost:8093'
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true