server:
  port: 8095

spring:
  application:
    name: msvc-annotation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/annotationsDb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

msvc:
  usuarios:
    url: http://localhost:8100
  proyectos:
    url: http://localhost:8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka